version: '3.8'

services:
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=jeopardy;Username=postgres;Password=postgres
      - SERVER_PORT=5000
    networks:
      - game-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jeopardy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - game-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

networks:
  game-network:
    driver: bridge

volumes:
  postgres-data: